version: "3"
services:

  consul:
    image: consul:0.7.0
    container_name: consul
    hostname: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command: "agent -dev -client 0.0.0.0"

  git2consul:
    image: cimpress/git2consul
    container_name: git2consul
    volumes:
      - ./tools:/tools
      - ./src/main/resources/git2consul:/git2consul
    entrypoint: >
      /tools/wait-for-it.sh consul:8500 --
      /usr/bin/node /usr/lib/node_modules/git2consul --endpoint consul
      --config-file /git2consul/Git2Consul-SpringConsulDemo-master.json

  vault:
    depends_on:
      - consul
    image: vault
    hostname: vault
    container_name: vault
    environment:
      VAULT_ADDR: 127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - ./tools/wait-for-it.sh:/wait-for-it.sh
      - ./config/vault:/config
      - ./config/vault/policies:/policies
    entrypoint: >
      /wait-for-it.sh consul:8500 -- vault server -config=/config/with-consul.hcl