version: "3"

services:

  springconsuldemo1:
    build:
      context: ./services/springconsuldemo1
    container_name: springconsuldemo1
    hostname: springconsuldemo1
    ports:
     - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VAULT_APP_TOKEN=${VAULT_APP_TOKEN}

  springconsuldemo2:
    build:
      context: ./services/springconsuldemo2
    container_name: springconsuldemo2
    hostname: springconsuldemo2
    ports:
     - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VAULT_APP_TOKEN=${VAULT_APP_TOKEN}
